services:
  email:
    image: golang:alpine
    working_dir: /go/src/email
    command: go run .
    volumes:
      - ./email:/go/src/email
      - ./ban:/go/src/ban

  ban:
    image: golang:alpine
    working_dir: /go/src/ban
    command: go run .
    volumes:
      - ./ban:/go/src/ban
      - ./email:/go/src/email
