services:
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  email:
    image: email_api
    build:
      dockerfile: ./email/Containerfile
    ports:
      - "5000:5000"

  ban:
    image: ban_api
    build:
      dockerfile: ./ban/Containerfile

  db:
    environment:
      POSTGRES_DB: email
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data:z
